<a href="https://colab.research.google.com/github/Alishapunw/Data-Science-Bootcamp/blob/Master---Homework-Assignments/PracticeAssignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally

In [ ]:
import numpy as np
np.random.seed(42)
A = np.random.randint(40, size=10)
B = np.random.randint(40, size=10)
print('This is the first array A:' ,A)
print('This is the second array B:' ,B)
x3 = np.vstack([A,B])
print('This is the vertically stacked array\n', x3)
x4 = np.hstack([A,B])
print('This is the horizontally stacked array\n', x4)

This is the first array A: [38 28 14  7 20 38 18 22 10 10]
This is the second array B: [23 35 39 23  2 21  1 23 29 37]
This is the vertically stacked array
 [[38 28 14  7 20 38 18 22 10 10]
 [23 35 39 23  2 21  1 23 29 37]]
This is the horizontally stacked array
 [38 28 14  7 20 38 18 22 10 10 23 35 39 23  2 21  1 23 29 37]


Q2. Find common elements between A and B.

In [ ]:
A = np.array([1,2,3])
B = np.array([4,5,1,2])
print('The common elements within set A and B are:' , np.intersect1d(A, B))

The common elements within set A and B are: [1 2]


Q3. Extract all numbers from A which are within a specific range. eg between 5 and 10.

In [ ]:
import numpy as np
A = np.random.randint(10, size=10)
print('This is A:', A)
B= np.zeros([0])
print('This is an empty numpy array B:', B)
j=0
for i in range(0,len(A)):
  if A[i] > 5 and A[i] <10:
    B = np.insert(B,j,A[i], 0)
    print(B)
    j+=1

print('This is the final output:' , B)

This is A: [5 8 3 1 9 5 4 7 3 4]
This is an empty numpy array B: []
[8.]
[8. 9.]
[8. 9. 7.]
This is the final output: [8. 9. 7.]


Q4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
	url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
	iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
print(iris_2d.shape)
solution = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)
iris_2d[solution]

(150, 4)


array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

Q5. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).



In [ ]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df.shape
print('Manufacturer  Model  Type\n')
for i in range(0,df.shape[0],20):
  print(df.Manufacturer[i],df.Model[i],df.Type[i])



Manufacturer  Model  Type

Acura Integra Small
Chrysler LeBaron Compact
Honda Prelude Sporty
Mercury Cougar Midsize
Subaru Loyale Small


Q6. Replace missing values in Min.Price and Max.Price columns with their respective mean.

```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [14]:
import pandas as pd
import numpy as np
df= pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df.rename(columns = {'Min.Price':'Min'}, inplace = True)
df.rename(columns = {'Max.Price':'Max'}, inplace = True)
for i in range(0,df.shape[0]):
 if (df.Min[i])== np.NaN:
    df.Min[i] = df["Min"].mean()
 if (df.Max[i] == np.NaN):
    df.Max[i] = df["Max"].mean()

Q7. How to get the rows of a dataframe with row sum > 100?

```
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

In [38]:
import pandas as pd
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
df.rename(columns = {1:'A'}, inplace = True)
df.rename(columns = {2:'B'}, inplace = True)
df.rename(columns = {3:'C'}, inplace = True)
for i in range(0,len(df)):
  if df.A[i] + df.B[i] + df.C[i] > 100:
    print("The row with sum > 100 is", i)

The row with sum > 100 is 0
The row with sum > 100 is 1
The row with sum > 100 is 8
The row with sum > 100 is 11
